### ISSUE TITLE
Feature: Documentation Guide - RSTUF Deployment and user flows

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf#227]
### What is the feature about?

This feature is about adding to the [RSTUF Guide](https://repository-service-tuf.readthedocs.io/en/latest/guide/index.html), section [Deployment](https://repository-service-tuf.readthedocs.io/en/latest/guide/deployment/server.html) a new chapter about Deployment Design, where it should give information about:

- Guide to size the RSTUF Deployment (number of Workers and API containers)
- Best practices for deploying RSTUF services
- How to proceed about signing Ceremony, Keys, and bootstrap
- [How to migrate existent packages](https://github.com/vmware/repository-service-tuf/issues/226)

### Services it relates to

repository-service-for-tuf

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MVrachev** [comment]
Also mention:
- How the user can use the task_id. Give some examples, maybe mention publishing targets.
