### ISSUE TITLE
Bug: `livenessProbe` in the example deployment causes containers to exit after creation

### ISSUE THREAD

**Issue by mayaCostantini** [repository-service-tuf/repository-service-tuf#398]
### What happened?

The [`livenessProbe`](https://github.com/repository-service-tuf/repository-service-tuf/blob/63807ec10bd03c292ed377cd7be3c42fbb5eb6a3/docs/source/guide/deployment/guide/k8s/deployment.yml#L26-L29) from [`deployment.yml`](https://github.com/repository-service-tuf/repository-service-tuf/blob/main/docs/source/guide/deployment/guide/k8s/deployment.yml) in the Kubernetes deployment guide executes the `exit 0` command which causes containers to exit after they are created.

### What behavior did you expect?

The livenessProbe should check the health of the container and not cause it to exit.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
Hi @mayaCostantini, thank you for filing this issue. It is a very important contribution to the RSTUF project!

Yes, there is a misusage of the `livenessProbe` in the [`deployment.yml`](https://github.com/repository-service-tuf/repository-service-tuf/blob/main/docs/source/guide/deployment/guide/k8s/deployment.yml). I will work fixing it.

**Comment by mayaCostantini** [comment]
Thanks @kairoaraujo !
