### ISSUE TITLE
Feature: rstuf state backups

### ISSUE THREAD

**Issue by fridex** [repository-service-tuf/repository-service-tuf#425]
### What is the feature about?

We would like to make sure the state of rstuf is preserved and eventually have a way to restore/replicate rstuf state to a testing environment. Is there a preferred way on how to perform backups of an rstuf deployment? Thanks!

### Services it relates to

repository-service-for-tuf

### Related tasks

https://github.com/repository-service-tuf/repository-service-tuf/issues/402

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
Hi @fridex, 

Thank you for the issue. We can improve our documentation for Repository Service for TUF (RSTUF) administrators. 

The RSTUF Worker has the core data of RSTUF, the TUF Metadata.
The current RSTUF Worker uses the [`RSTUF_STORAGE_BACKEND`](https://repository-service-tuf.readthedocs.io/en/stable/guide/repository-service-tuf-worker/Docker_README.html#required-rstuf-storage-backend); At the moment, it supports only [`LocalStorage`](https://repository-service-tuf.readthedocs.io/en/stable/guide/repository-service-tuf-worker/Docker_README.html#required-rstuf-storage-backend) type, which is a container volume. Backup the content of this volume (JSON files), saving a copy of the JSON files.

We are working also to support `AWSS3` type, which uses the AWS S3 objects, and in this case, is required to backup it using the AWS options.

RSTUF Worker uses the private online key as read-only [`RSTUF_KEYVAULT_BACKEND`](https://repository-service-tuf.readthedocs.io/en/stable/guide/repository-service-tuf-worker/Docker_README.html#required-rstuf-keyvault-backend). Currently, we support only [`LocalKeyVault`](https://repository-service-tuf.readthedocs.io/en/stable/guide/repository-service-tuf-worker/Docker_README.html#required-rstuf-keyvault-backend) type. Backup the content of this volume, saving a copy of the key.

The RSTUF Worker also uses a Postgres database to support high-traffic repositories, configured at the [`RSTUF_SQL_SERVER`](https://repository-service-tuf.readthedocs.io/en/stable/guide/repository-service-tuf-worker/Docker_README.html#required-rstuf-sql-server) variable. This database also needs a backup. The backup strategy depends on how you deploy the Postgres.

The RSTUF Worker and API also use the Redis services. It is required to backup the repository settings database id, also defined [`RSTUF_REDIS_SERVER`](https://repository-service-tuf.readthedocs.io/en/stable/guide/repository-service-tuf-worker/Docker_README.html#required-rstuf-redis-server) and by default id `1`, or customized id [`RSTUF_REDIS_SERVER_DB_REPO_SETTINGS`](https://repository-service-tuf.readthedocs.io/en/stable/guide/repository-service-tuf-worker/Docker_README.html#optional-rstuf-redis-server-db-repo-settings)

**Note:** The message queue [`RSTUF_BROKER_SERVER`](https://repository-service-tuf.readthedocs.io/en/stable/guide/repository-service-tuf-worker/Docker_README.html#required-rstuf-broker-server) and backend result [`RSTUF_REDIS_SERVER`](https://repository-service-tuf.readthedocs.io/en/stable/guide/repository-service-tuf-worker/Docker_README.html#required-rstuf-redis-server) (default db id `1` or custom id by [`RSTUF_REDIS_SERVER_DB_REPO_RESULT`](https://repository-service-tuf.readthedocs.io/en/stable/guide/repository-service-tuf-worker/Docker_README.html#optional-rstuf-redis-server-db-result)) for tasks are not required data for RSTUF. In some integration cases, you might want this information as well.

**Note:** RSTUF API only requires backup if you use the RSTUF API built-in authentication/authorization, which we do not advise using. Instead, we recommend using an API Gateway service/server to implement your authentication/authorization for the API requests.
If still, you're using it. Backuping your RSTUF API mapped to the [`RSTUF_DATA`](https://repository-service-tuf.readthedocs.io/en/stable/guide/repository-service-tuf-api/Docker_README.html#optional-data-dir).

To summarize:
- Backup the TUF Metadata stored in  [`RSTUF_STORAGE_BACKEND`](https://repository-service-tuf.readthedocs.io/en/stable/guide/repository-service-tuf-worker/Docker_README.html#required-rstuf-storage-backend)
- Backup the Private Online Key in the [`RSTUF_KEYVAULT_BACKEND`](https://repository-service-tuf.readthedocs.io/en/stable/guide/repository-service-tuf-worker/Docker_README.html#required-rstuf-keyvault-backend)
- Backup the Postgres RSTUF Database [`RSTUF_SQL_SERVER`](https://repository-service-tuf.readthedocs.io/en/stable/guide/repository-service-tuf-worker/Docker_README.html#required-rstuf-sql-server)
- Backup the Redis databases [`RSTUF_REDIS_SERVER`](https://repository-service-tuf.readthedocs.io/en/stable/guide/repository-service-tuf-worker/Docker_README.html#required-rstuf-redis-server)

Feature-wise, creating a restore mechanism for RSTUF from the TUF Metadata would also be possible. It will require some tests and investigation, but it could also be a simple strategy.

**Comment by fridex** [comment]
Thanks Kairo, this is definitely helpful. It looks like there are needed some lower level operations to make this happen. If there would be a native support for this feature that would be great. Thanks again!

**Comment by kairoaraujo** [comment]
I filed an issue to continue the idea as a feature. 😄 
Thanks, @fridex, for bringing it up.
