### ISSUE TITLE
Feature: Remove built-in Authn/z from RSTUF

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf#491]
### What is the feature about?

It was introduced in the prototype of RSTUF API.

This feature allows users to deploy RSTUF and use the authentication and authorization based on scopes for the RSTUF API.

This is to discuss about removing this feature.
[We already recommend our users use some external API authentication and authorization if it needs to be public.](https://repository-service-tuf.readthedocs.io/en/stable/guide/deployment/planning/deployment.html#authentication-authorization)

Use case example:
For example, in cases of RubyGems or PyPI, the API for managing artifacts should be accessible only for the Distribution Platforms.
The APIs for management (update metadata, signing, etc.) should have an authen/z based on their governance policies/RBAC. That can be achieved by creating an interface on their platform, remote access using VPN, API Gateway using their SSO authentication, etc. 

IMHO this feature:
- Is out of scope of RSTUF (TUF)
- It brings more risk than values
- Depending on the bug, it can be very dangerous for our users

It has already brought a lot of problems as I can list
- https://github.com/repository-service-tuf/repository-service-tuf-cli/issues/397
- https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/259
- https://github.com/repository-service-tuf/repository-service-tuf-api/issues/175
- https://github.com/repository-service-tuf/repository-service-tuf-api/pull/264
- https://github.com/repository-service-tuf/repository-service-tuf-api/pull/318
- https://github.com/repository-service-tuf/repository-service-tuf-api/issues/324
...

### Services it relates to

repository-service-for-tuf-cli, repository-service-for-tuf-api

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MVrachev** [comment]
TODO:

- [ ] remove all issues related to authentication and authorization
- [ ] remove all prs related to authentication and authorization

**Comment by kairoaraujo** [comment]
I'm closing this issue.
