### ISSUE TITLE
Task: Migrate FT to use the RSTUF `admin2` (new admin)

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf#686]
### What is the task about?

Migrate the FT to use the RSTUF admin2 (new admin CLI) for the user interaction simulation (ceremony, sign, metadata update)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MVrachev** [comment]
Issues #https://github.com/repository-service-tuf/repository-service-tuf/pull/687 and #703 are closing this issue.
