### ISSUE TITLE
RSTUF Security Audit

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf#833]
### Hi RSTUF Community!

A few months ago, we initiated the RSTUF funding for a security audit in collaboration with the [OpenSSF](https://github.com/ossf/tac/issues/379). This marks an exciting step forward in enhancing the security and reliability of our project.

#### Community Meeting Update

Today, December 4th, 2024, we welcomed the [Open Source Technology Improvement Fund (OSTIF)](https://ostif.org/) to our community meeting. A special thank you to @Amir-Montazery for joining us and representing OSTIF during the discussion.

You can watch the recording of the meeting here:

[Link to the meeting recording](https://zoom.us/rec/share/0bkIYEKEqOJpp4XNshwKUsQrslRpcb8rDahPiaRDJcY2P3fK59HfxlyDnWrpc5E.YRjjht79WplMxuKd)

Get Involved: Share Your Feedback

In the spirit of full transparency, we are opening this issue to gather your input. This is your opportunity to:

Share comments and feedback

Ask any questions

Vote in favor (👍) or against (👎) the audit, scheduled to begin in Q1/Q2 2025.

Important: Please cast your votes in the summary section of the issue.

Timeline

We will close this issue on December 15th, 2024, so make sure to share your feedback and vote before then.

Thank you for your engagement and support in making RSTUF stronger and more secure!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
@MVrachev 
@rdimitrov 
@KAUTH 
@simi 
@ewdurbin 
@lukpueh

**Comment by simi** [comment]
Yes please! 💪

**Comment by rdimitrov** [comment]
Sounds good! 👍 Thank you for driving the initiative 🙌

**Comment by kairoaraujo** [comment]
We will meet at the beginning of the 2025 to discuss it.
Closing this issue.
Thank you for all that vote!
