### ISSUE TITLE
Bug: Invalid workflow file - ci.yml

### ISSUE THREAD

**Issue by rdimitrov** [repository-service-tuf/repository-service-tuf#98]
### What happened?

The workflow is not valid. .github/workflows/ci.yml (Line: 24, Col: 21): Invalid secret, GITHUB_TOKEN is not defined in the referenced workflow.

For reference - https://github.com/vmware/repository-service-tuf/actions/runs/3343516837/workflow

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
The problem is also that we cannot do it for pull requests. 
Needs investigation

**Comment by rdimitrov** [comment]
Here's an explanation of the reason for that error - https://github.com/orgs/community/discussions/26749#discussioncomment-3253230

We should discuss if we need to have a workflow_call trigger for that workflow and if so add the necessary declarations to the workflow_call object 👍

**Comment by kairoaraujo** [comment]
> Here's an explanation of the reason for that error - https://github.com/orgs/community/discussions/26749#discussioncomment-3253230
> 
> We should discuss if we need to have a workflow_call trigger for that workflow and if so add the necessary declarations to the workflow_call object 👍

We need the `workflow_call` trigger for https://github.com/vmware/repository-service-tuf-worker/issues/117

We need run it before releasing 
[WIP]
https://github.com/vmware/repository-service-tuf-worker/blob/d3f48ba79eba5007dd16551b6d14146bd4efcdc2/.github/workflows/cd.yml#L10-L15
